### ISSUE TITLE
The first time to resume play on lock screen widget is malfunction.

### ISSUE THREAD

**Issue by alfredoyang** [totality-of-life/testing-ios#20]
It has bothered me for a while that I can't control app on lock screen. Now the new widget is added, thank you!
However, I found one small issue:
The first time to resume playing isn't work with followings steps.

1. remove "total life" app from recent used app list.
2. start the "total life app" and play any audio file.
3. pause the playback on the app.
4. push power button to enter the lock screen.
5. push the play button on the widget, but it doesn't resume playback. It stops automatically and you need to push the play button again.

If you can't reproduce it, please let me know, I'll send you a reproduced video.

**Comment by totality-of-life** [comment]
I forget to update the playback state on pause. Thanks.

**Comment by totality-of-life** [comment]
Fixed with 2.0 (80).

**Comment by alfredoyang** [comment]
I just tried the latest version (80), the problem is still there.
I uploaded a reproduced video at [https://youtu.be/Ld8lF3sFiOA](https://youtu.be/Ld8lF3sFiOA).

**Comment by totality-of-life** [comment]
please try  version 85

**Comment by alfredoyang** [comment]
Version 91 fixed most part of this bug except for playing with bluetooth speaker (or earphone).

Reproduce steps:
1. connect with a bluetooth speaker (it needs to have a play/pause button)
2. playing any audio file in total life
3. pause playback by pressing play/pause button on speaker
4. wait for 1 minute
5. resume playback by pressing play/pause button on speaker

Result:
Step 5 brings up play widget on lock screen but it's in pause state. You need to press the bluetooth button again to resume. 

PS: I haven't tried other bluetooth devices yet but I think it should be able to reproduce with others as long as they get a play/resume button.

**Comment by totality-of-life** [comment]
I reproduced the bug with my [Boom 3](https://www.ultimateears.com/zh-tw/wireless-speakers/boom-3.html).
I am trying to fix. Thanks.

**Comment by totality-of-life** [comment]
Please try version 93.

cased by:

https://developer.apple.com/documentation/avfaudio/avaudiosession/1616596-interruptionnotification
If you configured your audio session to be nonmixable (the default behavior for the playback, playAndRecord, soloAmbient, and multiRoute categories), deactivate your audio session if you’re not actively using audio when you go into the background. Doing so avoids having your audio session deactivated by the system (and receiving this somewhat confusing notification).

**Comment by alfredoyang** [comment]
Fixed confirmed in 93, thank you.
